version: "3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-tpfoyer:
    image: oussama22444/devops:latest
    container_name: backend
    restart: on-failure
    ports:
      - 8091:8091
    depends_on:
     - mysqldb
volumes:
  db:
